chore(endo-load): ts-check up to contents vs. FileModule (WIP)
src/endo-load.js:78:13 - error TS2339: Property 'contents' does not exist on type 'Compartment'.

78     const { contents, modules } = compartmap.compartments[loc];